version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: training-calendar-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: training_calendar
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - training-calendar-network

  # Flask Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: training-calendar-backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/training_calendar?authSource=admin
      FLASK_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - training-calendar-network
    volumes:
      - ./backend:/app
      - /app/__pycache__

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: training-calendar-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - training-calendar-network

volumes:
  mongodb_data:
    driver: local

networks:
  training-calendar-network:
    driver: bridge 