version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: training-calendar-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: training_calendar
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - training-calendar-network-dev

  # Flask Backend (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: training-calendar-backend-dev
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/training_calendar?authSource=admin
      FLASK_ENV: development
      FLASK_DEBUG: 1
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - training-calendar-network-dev
    volumes:
      - ./backend:/app
      - /app/__pycache__

  # React Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: training-calendar-frontend-dev
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - training-calendar-network-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data_dev:
    driver: local

networks:
  training-calendar-network-dev:
    driver: bridge 